services:
  cloud_minio:
    container_name: cloud_minio
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/cloud_minio/data:/data
    environment:
      MINIO_ROOT_USER: nhatvy1
      MINIO_ROOT_PASSWORD: 123456789
    command: server /data --console-address ":9001"
